name: memoriaviva
description: "App de lembretes"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.0.15
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  image_picker: ^0.8.7+3
  http: ^0.13.4
  translator: ^0.1.7
  path_provider: ^2.0.11
  awesome_notifications: ^0.10.0
  just_audio: ^0.9.10
  permission_handler: ^11.3.1
  device_info_plus: ^11.1.0
  android_intent_plus: ^5.2.0
  package_info_plus: ^8.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/logo.png
    - assets/logo_notext.png
    - assets/images/
    - assets/sounds/alarm_sound.mp3
